#pragma once

#include "c_cvars.h"

class IFXAAShader {
public:
  enum Quality { None, Low, Medium, High, Extreme, Count };
};

//==========================================================================
//
// CVARs
//
//==========================================================================
EXTERN_CVAR(Bool, gl_bloom)
EXTERN_CVAR(Float, gl_bloom_amount)
EXTERN_CVAR(Float, gl_exposure_scale)
EXTERN_CVAR(Float, gl_exposure_min)
EXTERN_CVAR(Float, gl_exposure_base)
EXTERN_CVAR(Float, gl_exposure_speed)
EXTERN_CVAR(Int, gl_tonemap)
EXTERN_CVAR(Int, gl_atmosphere)
EXTERN_CVAR(Float, gl_atmosphere_intensity)
EXTERN_CVAR(Float, gl_atmosphere_contrast)
EXTERN_CVAR(Int, gl_bloom_kernel_size)
EXTERN_CVAR(Bool, gl_lens)
EXTERN_CVAR(Float, gl_lens_k)
EXTERN_CVAR(Float, gl_lens_kcube)
EXTERN_CVAR(Float, gl_lens_chromatic)
EXTERN_CVAR(Int, gl_fxaa)
EXTERN_CVAR(Int, gl_ssao)
EXTERN_CVAR(Int, gl_ssao_portals)
EXTERN_CVAR(Float, gl_ssao_strength)
EXTERN_CVAR(Int, gl_ssao_debug)
EXTERN_CVAR(Float, gl_ssao_bias)
EXTERN_CVAR(Float, gl_ssao_radius)
EXTERN_CVAR(Float, gl_ssao_blur)
EXTERN_CVAR(Float, gl_ssao_exponent)
EXTERN_CVAR(Float, gl_paltonemap_powtable)
EXTERN_CVAR(Bool, gl_paltonemap_reverselookup)
EXTERN_CVAR(Float, gl_menu_blur)
EXTERN_CVAR(Bool, bd_bloom_enable)
EXTERN_CVAR(Float, bd_bloom_strength)
EXTERN_CVAR(Float, vid_brightness)
EXTERN_CVAR(Float, vid_contrast)
EXTERN_CVAR(Float, vid_saturation)
EXTERN_CVAR(Int, bd_graphics_preset)
EXTERN_CVAR(Bool, bd_preset_locked)
EXTERN_CVAR(Bool, bd_postfx_enable)
EXTERN_CVAR(Int, bd_postfx_quality)
EXTERN_CVAR(Bool, bd_vignette_enable)
EXTERN_CVAR(Float, bd_vignette_strength)
EXTERN_CVAR(Bool, bd_chromatic_enable)
EXTERN_CVAR(Float, bd_chromatic_strength)
EXTERN_CVAR(Bool, bd_filmgrain_enable)
EXTERN_CVAR(Float, bd_filmgrain_strength)
EXTERN_CVAR(Float, bd_filmgrain_scale)
EXTERN_CVAR(Bool, bd_sharpen_enable)
EXTERN_CVAR(Float, bd_sharpen_strength)
EXTERN_CVAR(Bool, bd_retro_pixel_enable)
EXTERN_CVAR(Float, bd_retro_pixel_scale)
EXTERN_CVAR(Bool, bd_vhs_enable)
EXTERN_CVAR(Float, bd_vhs_strength)
EXTERN_CVAR(Float, bd_vhs_scanline)
EXTERN_CVAR(Float, bd_vhs_jitter)
EXTERN_CVAR(Float, bd_vhs_tracking)
EXTERN_CVAR(Float, bd_vhs_ghosting)
EXTERN_CVAR(Float, bd_vhs_noise)
EXTERN_CVAR(Float, bd_vhs_evil)
EXTERN_CVAR(Bool, bd_vhs_panic_enable)
EXTERN_CVAR(Float, bd_colorgrade_strength)
EXTERN_CVAR(Int, bd_colorgrade_mode)
EXTERN_CVAR(Int, bd_colorgrade_lut)
EXTERN_CVAR(Int, bd_dynlight_falloff_mode)
EXTERN_CVAR(Float, bd_dynlight_falloff_exponent)
EXTERN_CVAR(Float, bd_emissive_boost)
EXTERN_CVAR(Bool, bd_gi_ambient_enable)
EXTERN_CVAR(Float, bd_gi_ambient_strength)
EXTERN_CVAR(Bool, bd_sprite_lighting_refine)
EXTERN_CVAR(Int, bd_fog_mode)
EXTERN_CVAR(Float, bd_sector_fog_scale)
EXTERN_CVAR(Int, gl_satformula)
EXTERN_CVAR(Int, gl_crt_mode)
EXTERN_CVAR(Float, gl_crt_distortion)
EXTERN_CVAR(Float, gl_crt_zoom)
EXTERN_CVAR(Float, gl_crt_scanline)
EXTERN_CVAR(Float, gl_crt_scanline_density)
EXTERN_CVAR(Float, gl_crt_scanline_sharpness)
EXTERN_CVAR(Float, gl_crt_mask_intensity)
EXTERN_CVAR(Int, gl_ntsc_mode)
