#!/usr/bin/env python3
"""Interactive launcher for the BiasedDoom Python examples.

Pick an example with the arrow keys, press ENTER, play. No packaging,
no command-line flags to remember.

    tools/play-python-example.py

Optional environment overrides:
    BIASEDDOOM_EXE   engine binary   (default: build/biaseddoom, then build-release/)
    BIASEDDOOM_IWAD  Doom IWAD path  (auto-detected otherwise)
"""

import curses
import os
import shutil
import subprocess
import sys
import tempfile

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
EXAMPLES_DIR = os.path.join(REPO_ROOT, "examples", "python")

IWAD_CANDIDATES = [
    os.environ.get("BIASEDDOOM_IWAD", ""),
    os.environ.get("DOOMWADDIR", "") and os.path.join(os.environ["DOOMWADDIR"], "doom2.wad"),
    os.path.expanduser("~/games/doom2.wad"),
    os.path.expanduser("~/.config/biaseddoom/doom2.wad"),
    os.path.expanduser("~/.config/gzdoom/doom2.wad"),
    "/usr/share/games/doom/doom2.wad",
    "/usr/local/share/games/doom/doom2.wad",
]

ENGINE_CANDIDATES = [
    os.environ.get("BIASEDDOOM_EXE", ""),
    os.path.join(REPO_ROOT, "build", "biaseddoom"),
    os.path.join(REPO_ROOT, "build-release", "biaseddoom"),
]

# Extra one-line hints shown before launching specific examples.
LAUNCH_HINTS = {
    "13_bullet_time": "The Q key is auto-bound to User1 for this run: HOLD Q for bullet time.",
    "15_roguelike_run": "A 'roguelike.zds' checkpoint is auto-saved on every map load.",
    "19_elemental_squads": "Press User2 (bind g +user2) to toggle all squad tints.",
}

# Examples that need the User1 key; we auto-bind Q for them via a temp exec cfg.
NEEDS_USER1 = {"13_bullet_time"}


def find_first(paths):
    for path in paths:
        if path and os.path.isfile(path):
            return path
    return None


def example_description(path):
    """First prose line of the example's README.md."""
    readme = os.path.join(path, "README.md")
    try:
        with open(readme, encoding="utf-8") as handle:
            for line in handle:
                line = line.strip()
                if line and not line.startswith("#"):
                    return line[:90]
    except OSError:
        pass
    return ""


def discover_examples():
    examples = []
    for name in sorted(os.listdir(EXAMPLES_DIR)):
        path = os.path.join(EXAMPLES_DIR, name)
        if os.path.isdir(path) and os.path.isfile(os.path.join(path, "PYTHON")):
            examples.append((name, example_description(path)))
    return examples


def launch(example, iwad, engine, headless):
    cmd = [engine, "-iwad", iwad, "-python", "-file", os.path.join(EXAMPLES_DIR, example)]
    if headless:
        cmd += ["-stdout", "-nosound", "-nointro", "+map", "map01", "-scripttest", "350"]
        if not os.environ.get("DISPLAY"):
            xvfb = shutil.which("xvfb-run")
            if xvfb is None:
                print("\n  error: headless test needs a display; install xvfb (or run on a desktop)\n")
                return 1
            cmd = [xvfb, "-a"] + cmd
    else:
        cmd += ["+map", "map01"]

    exec_cfg = None
    if example in NEEDS_USER1 and not headless:
        exec_cfg = tempfile.NamedTemporaryFile(
            mode="w", suffix=".cfg", prefix="biaseddoom-example-", delete=False)
        exec_cfg.write("// auto-generated by play-python-example.py\nbind q +user1\n")
        exec_cfg.close()
        cmd += ["+exec", exec_cfg.name]

    print()
    print("  Launching: %s" % example)
    if example in LAUNCH_HINTS:
        print("  Hint: %s" % LAUNCH_HINTS[example])
    print()
    print("  $ %s" % " ".join(cmd))
    print()
    print("  (the engine window opens now; quit the game to come back here)")
    print()
    sys.stdout.flush()
    try:
        return subprocess.call(cmd)
    finally:
        if exec_cfg is not None:
            os.unlink(exec_cfg.name)


def menu(stdscr, examples, iwad, engine):
    curses.curs_set(0)
    selected = 0
    top = 0
    while True:
        stdscr.erase()
        height, width = stdscr.getmaxyx()
        title = "BiasedDoom -- Python examples"
        stdscr.addnstr(0, 2, title, width - 4, curses.A_BOLD)
        stdscr.addnstr(1, 2, "IWAD: %s" % iwad, width - 4, curses.A_DIM)
        stdscr.addnstr(2, 2, "engine: %s" % engine, width - 4, curses.A_DIM)
        stdscr.addnstr(3, 2, "up/down: choose    ENTER: play    t: headless test    q: quit",
                       width - 4, curses.A_REVERSE)

        visible = height - 6
        if selected < top:
            top = selected
        elif selected >= top + visible:
            top = selected - visible + 1
        for row, (name, desc) in enumerate(examples[top:top + visible]):
            y = 5 + row
            index = top + row
            attr = curses.A_STANDOUT if index == selected else curses.A_NORMAL
            label = " %-28s %s" % (name, desc)
            stdscr.addnstr(y, 2, label, width - 4, attr)

        key = stdscr.getch()
        if key in (curses.KEY_UP, ord("k")):
            selected = (selected - 1) % len(examples)
        elif key in (curses.KEY_DOWN, ord("j")):
            selected = (selected + 1) % len(examples)
        elif key in (curses.KEY_ENTER, 10, 13):
            return examples[selected][0], False
        elif key in (ord("t"), ord("T")):
            return examples[selected][0], True
        elif key in (ord("q"), ord("Q"), 27):
            return None, False


def numbered_fallback(examples, iwad, engine):
    """Plain numbered menu for terminals where curses does not work."""
    print("BiasedDoom -- Python examples")
    print("IWAD: %s" % iwad)
    print("engine: %s" % engine)
    print()
    for i, (name, desc) in enumerate(examples, 1):
        print("  %2d. %-28s %s" % (i, name, desc))
    print()
    print("  type a number + ENTER to play, 't<number>' for a headless test, 'q' to quit")
    while True:
        try:
            choice = input("> ").strip().lower()
        except (EOFError, KeyboardInterrupt):
            return None, False
        if choice == "q":
            return None, False
        headless = choice.startswith("t")
        if headless:
            choice = choice[1:]
        if choice.isdigit() and 1 <= int(choice) <= len(examples):
            return examples[int(choice) - 1][0], headless
        print("  huh? pick 1-%d, t1-t%d, or q" % (len(examples), len(examples)))


def main():
    engine = find_first(ENGINE_CANDIDATES)
    iwad = find_first(IWAD_CANDIDATES)
    examples = discover_examples()

    if not examples:
        sys.exit("no examples found under %s" % EXAMPLES_DIR)
    problems = []
    if engine is None:
        problems.append("engine binary not found (build it first, or set BIASEDDOOM_EXE)")
    if iwad is None:
        problems.append("no doom2.wad found (set BIASEDDOOM_IWAD=/path/to/doom2.wad)")
    if problems:
        for problem in problems:
            print("error: %s" % problem, file=sys.stderr)
        sys.exit(1)

    while True:
        try:
            choice, headless = curses.wrapper(menu, examples, iwad, engine)
        except curses.error:
            choice, headless = numbered_fallback(examples, iwad, engine)
        if choice is None:
            print("bye!")
            return
        launch(choice, iwad, engine, headless)
        try:
            input("press ENTER to return to the menu...")
        except (EOFError, KeyboardInterrupt):
            print()
            return


if __name__ == "__main__":
    main()
